---
 - name: Nginx Ingress Setup Play
   hosts: k8s-master
   gather_facts: false
   
   tasks:
     - name: checking Helm tool is installed or not
       shell: whereis helm | egrep -o "/usr/local/bin/helm|/usr/bin/helm"
       register: out
       failed_when: false
       changed_when: false
     
     - name: Installing Helm tool
       shell: |
               yum install wget -y
               wget https://get.helm.sh/helm-v3.6.3-linux-amd64.tar.gz
               tar -zxf helm-v3.6.3-linux-amd64.tar.gz
               mv linux-amd64/helm /usr/local/bin/
       when: "'helm' not in out.stdout"
  
     - debug:
         msg: Already Helm tool is installed
       when: "'helm' in out.stdout"

     - name: Creating new namespace for Nginx Ingress
       command: kubectl create ns nginx-ingress
      
     - name: Adding Nginx Ingress repo and updating helm repo
       shell: |
               helm repo add nginx-ingress https://kubernetes.github.io/ingress-nginx
               helm repo update
     
     - name: Installing Nginx Ingress Controller
       shell: |
               helm install nginx-ingress nginx-ingress/ingress-nginx -n nginx-ingress > /tmp/nginx-ingress.outs

     - name: Verify Installation
       shell: |
               helm list --all-namespaces
       register: outs
     - debug: var=outs.stdout_lines
